# Generated by Django 3.1.6 on 2021-02-09 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricecard',
            options={'verbose_name': 'Цены', 'verbose_name_plural': 'Цены'},
        ),
    ]
